insert into User (firstName, lastName) values 
	('Elros Tar', 'Minyatur'),
	('Vardamir', 'Nólimon'),
	('Tar', 'Amandil'),
	('Tar', 'Elendil'),
	('Tar', 'Meneldur Írimon'),
	('Tar', 'Aldarion Anardil'),
	('Tar', 'Ancalimë'),
	('Tar', 'Anárion'),
	('Tar', 'Súrion'),
	('Tar', 'Telperiën'),
	('Tar', 'Minastir'),
	('Tar', 'Ciryatan'),
	('Tar', 'Atanamir'),
	('Tar', 'Ancalimon'),
	('Tar', 'Telemmaitë'),
	('Tar', 'Vanimeldë'),
	('Tar', 'Anducal'),
	('Tar', 'Alcarin'),
	('Tar', 'Calmacil'),
	('Tar', 'Ardamin'),
	('Tar', 'Herunúmen'),
	('Tar', 'Hostamir'),
	('Tar', 'Falassion'),
	('Tar', 'Telemnar'),
	('Tar', 'Palantir'),
	('Tar', 'Míriel'),
	('Tar', 'Calion'),
	('Ingwë', ''),
	('Finwë', ''),
	('Fangorn', ''),
	('Finglas', ''),
	('Fladrif', ''),
	('Beechbone', ''),
	('Bregalad', ''),
	('Fimbrethil', '');
	
insert into UserEmail (user_id, address) values 
	(00, 'elros-tar-minyatur@armenelos.me'),
	(01, 'vardamir-nolimon@armenelos.me'),
	(02, 'tar-amandil@armenelos.me'),
	(03, 'tar-elendil@armenelos.me'),
	(04, 'tar-meneldur-irimon@armenelos.me'),
	(05, 'tar-aldarion-anardil@armenelos.me'),
	(06, 'tar-ancalime@armenelos.me'),
	(07, 'tar-anarion@armenelos.me'),
	(08, 'tar-surion@armenelos.me'),
	(09, 'tar-telperien@armenelos.me'),
	(10, 'tar-minastir@armenelos.me'),
	(11, 'tar-ciryatan@armenelos.me'),
	(12, 'tar-atanamir@armenelos.me'),
	(13, 'tar-ancalimon@armenelos.me'),
	(14, 'tar-telemmaite@armenelos.me'),
	(15, 'tar-vanimelde@armenelos.me'),
	(16, 'tar-anducal@armenelos.me'),
	(17, 'tar-alcarin@armenelos.me'),
	(18, 'tar-calmacil@armenelos.me'),
	(19, 'tar-ardamin@armenelos.me'),
	(20, 'tar-herunumen@armenelos.me'),
	(21, 'tar-hostamir@armenelos.me'),
	(22, 'tar-falassion@armenelos.me'),
	(23, 'tar-telemnar@armenelos.me'),
	(24, 'tar-palantir@armenelos.me'),
	(25, 'tar-miriel@armenelos.me'),
	(26, 'ingwe@vanyar.vlr'),
	(27, 'finwe@vanyar.vlr'),
	(28, 'fangorn@fangorn.me'),
	(29, 'finglas@fangorn.me'),
	(30, 'fladrif@fangorn.me'),
	(31, 'beechbone@fangorn.me'),
	(32, 'bregalad@fangorn.me'),
	(33, 'fimbrethil@fangorn.me');

