insert into Role (name, type) values 
  ('GUEST', 'ENVIRONMENT'),
  ('STUDENT', 'ENVIRONMENT'),
  ('TEACHER', 'ENVIRONMENT'),
  ('SERVANT_OF_SAURON', 'ENVIRONMENT'),
  ('WORKSPACE_STUDENT', 'WORKSPACE'),
  ('WORKSPACE_TEACHER', 'WORKSPACE');