/* 
 * Users
 * 
 * 01 - 27: Rulers of Númenor (in student environment role)
 * 28 - 29: Vanyars Ingwë & Finwë (in guest role)
 * 30 - 35: Ents (in teacher role),
 * 36 - 37: Nazgûls (in Servant of Sauron role)
 * 38: Saruman (in Servant of Sauron role)
 * */
insert into User (id, firstName, lastName, role_id) values 
	(1, 'Elros Tar', 'Minyatur', (select id from ROLE where name = 'STUDENT')),
	(2, 'Vardamir', 'Nólimon', (select id from ROLE where name = 'STUDENT')),
	(3, 'Tar', 'Amandil', (select id from ROLE where name = 'STUDENT')),
	(4, 'Tar', 'Elendil', (select id from ROLE where name = 'STUDENT')),
	(5, 'Tar', 'Meneldur Írimon', (select id from ROLE where name = 'STUDENT')),
	(6, 'Tar', 'Aldarion Anardil', (select id from ROLE where name = 'STUDENT')),
	(7, 'Tar', 'Ancalimë', (select id from ROLE where name = 'STUDENT')),
	(8, 'Tar', 'Anárion', (select id from ROLE where name = 'STUDENT')),
	(9, 'Tar', 'Súrion', (select id from ROLE where name = 'STUDENT')),
	(10, 'Tar', 'Telperiën', (select id from ROLE where name = 'STUDENT')),
	(11, 'Tar', 'Minastir', (select id from ROLE where name = 'STUDENT')),
	(12, 'Tar', 'Ciryatan', (select id from ROLE where name = 'STUDENT')),
	(13, 'Tar', 'Atanamir', (select id from ROLE where name = 'STUDENT')),
	(14, 'Tar', 'Ancalimon', (select id from ROLE where name = 'STUDENT')),
	(15, 'Tar', 'Telemmaitë', (select id from ROLE where name = 'STUDENT')),
	(16, 'Tar', 'Vanimeldë', (select id from ROLE where name = 'STUDENT')),
	(17, 'Tar', 'Anducal', (select id from ROLE where name = 'STUDENT')),
	(18, 'Tar', 'Alcarin', (select id from ROLE where name = 'STUDENT')),
	(19, 'Tar', 'Calmacil', (select id from ROLE where name = 'STUDENT')),
	(20, 'Tar', 'Ardamin', (select id from ROLE where name = 'STUDENT')),
	(21, 'Tar', 'Herunúmen', (select id from ROLE where name = 'STUDENT')),
	(22, 'Tar', 'Hostamir', (select id from ROLE where name = 'STUDENT')),
	(23, 'Tar', 'Falassion', (select id from ROLE where name = 'STUDENT')),
	(24, 'Tar', 'Telemnar', (select id from ROLE where name = 'STUDENT')),
	(25, 'Tar', 'Palantir', (select id from ROLE where name = 'STUDENT')),
	(26, 'Tar', 'Míriel', (select id from ROLE where name = 'STUDENT')),
	(27, 'Tar', 'Calion', (select id from ROLE where name = 'STUDENT')),
	(28, 'Ingwë', '', (select id from ROLE where name = 'GUEST')),
	(29, 'Finwë', '', (select id from ROLE where name = 'GUEST')),
	(30, 'Fangorn', '', (select id from ROLE where name = 'TEACHER')),
	(31, 'Finglas', '', (select id from ROLE where name = 'TEACHER')),
	(32, 'Fladrif', '', (select id from ROLE where name = 'TEACHER')),
	(33, 'Beechbone', '', (select id from ROLE where name = 'TEACHER')),
	(34, 'Bregalad', '', (select id from ROLE where name = 'TEACHER')),
	(35, 'Fimbrethil', '', (select id from ROLE where name = 'TEACHER')),
	(36, 'Witch-king Of Angmar', '', (select id from ROLE where name = 'SERVANT_OF_SAURON')),
	(37, 'Khamûl', '', (select id from ROLE where name = 'SERVANT_OF_SAURON')),
	(38, 'Saruman', 'The White', (select id from ROLE where name = 'SERVANT_OF_SAURON'));
	
insert into UserEmail (user_id, address) values 
	(1, 'elros-tar-minyatur@armenelos.me'),
	(2, 'vardamir-nolimon@armenelos.me'),
	(3, 'tar-amandil@armenelos.me'),
	(4, 'tar-elendil@armenelos.me'),
	(5, 'tar-meneldur-irimon@armenelos.me'),
	(6, 'tar-aldarion-anardil@armenelos.me'),
	(7, 'tar-ancalime@armenelos.me'),
	(8, 'tar-anarion@armenelos.me'),
	(9, 'tar-surion@armenelos.me'),
	(10, 'tar-telperien@armenelos.me'),
	(11, 'tar-minastir@armenelos.me'),
	(12, 'tar-ciryatan@armenelos.me'),
	(13, 'tar-atanamir@armenelos.me'),
	(14, 'tar-ancalimon@armenelos.me'),
	(15, 'tar-telemmaite@armenelos.me'),
	(16, 'tar-vanimelde@armenelos.me'),
	(17, 'tar-anducal@armenelos.me'),
	(18, 'tar-alcarin@armenelos.me'),
	(19, 'tar-calmacil@armenelos.me'),
	(20, 'tar-ardamin@armenelos.me'),
	(21, 'tar-herunumen@armenelos.me'),
	(22, 'tar-hostamir@armenelos.me'),
	(23, 'tar-falassion@armenelos.me'),
	(24, 'tar-telemnar@armenelos.me'),
	(25, 'tar-palantir@armenelos.me'),
	(26, 'tar-miriel@armenelos.me'),
	(27, 'tar-calion@armenelos.me'),
	(28, 'ingwe@highelves-vanyar.me'),
	(29, 'finwe@highelves-vanyar.me'),
	(28, 'ingwe@valinor.aman'),
	(29, 'finwe@valinor.aman'),
	(30, 'fangorn@fangorn.me'),
	(31, 'finglas@fangorn.me'),
	(32, 'fladrif@fangorn.me'),
	(33, 'beechbone@fangorn.me'),
	(34, 'bregalad@fangorn.me'),
	(35, 'fimbrethil@fangorn.me'),
	(36, 'witchking@minasmorgul.me'),
	(37, 'khamul@minasmorgul.me'),
	(38, 'sarumanwhite@isengard.me');
