/* 
 * Users
 * 
 * 00 - 25: Rulers of Númenor (in student environment role)
 * 26 - 27: Vanyars Ingwë & Finwë (in guest role)
 * 28 - 33: Ents (in teacher role),
 * 34 - 35: Nazgûls (in Servant of Sauron role)
 * 36: Saruman (in Servant of Sauron role)
 * */
insert into User (firstName, lastName, role_id) values 
	('Elros Tar', 'Minyatur', (select id from ROLE where name = 'STUDENT')),
	('Vardamir', 'Nólimon', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Amandil', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Elendil', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Meneldur Írimon', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Aldarion Anardil', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Ancalimë', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Anárion', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Súrion', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Telperiën', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Minastir', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Ciryatan', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Atanamir', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Ancalimon', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Telemmaitë', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Vanimeldë', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Anducal', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Alcarin', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Calmacil', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Ardamin', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Herunúmen', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Hostamir', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Falassion', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Telemnar', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Palantir', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Míriel', (select id from ROLE where name = 'STUDENT')),
	('Tar', 'Calion', (select id from ROLE where name = 'STUDENT')),
	('Ingwë', '', (select id from ROLE where name = 'GUEST')),
	('Finwë', '', (select id from ROLE where name = 'GUEST')),
	('Fangorn', '', (select id from ROLE where name = 'TEACHER')),
	('Finglas', '', (select id from ROLE where name = 'TEACHER')),
	('Fladrif', '', (select id from ROLE where name = 'TEACHER')),
	('Beechbone', '', (select id from ROLE where name = 'TEACHER')),
	('Bregalad', '', (select id from ROLE where name = 'TEACHER')),
	('Fimbrethil', '', (select id from ROLE where name = 'TEACHER')),
	('Witch-king Of Angmar', '', (select id from ROLE where name = 'SERVANT_OF_SAURON')),
	('Khamûl', '', (select id from ROLE where name = 'SERVANT_OF_SAURON')),
	('Saruman', 'The White', (select id from ROLE where name = 'SERVANT_OF_SAURON'));
	
insert into UserEmail (user_id, address) values 
	((select min(id) from User) + 00, 'elros-tar-minyatur@armenelos.me'),
	((select min(id) from User) + 01, 'vardamir-nolimon@armenelos.me'),
	((select min(id) from User) + 02, 'tar-amandil@armenelos.me'),
	((select min(id) from User) + 03, 'tar-elendil@armenelos.me'),
	((select min(id) from User) + 04, 'tar-meneldur-irimon@armenelos.me'),
	((select min(id) from User) + 05, 'tar-aldarion-anardil@armenelos.me'),
	((select min(id) from User) + 06, 'tar-ancalime@armenelos.me'),
	((select min(id) from User) + 07, 'tar-anarion@armenelos.me'),
	((select min(id) from User) + 08, 'tar-surion@armenelos.me'),
	((select min(id) from User) + 09, 'tar-telperien@armenelos.me'),
	((select min(id) from User) + 10, 'tar-minastir@armenelos.me'),
	((select min(id) from User) + 11, 'tar-ciryatan@armenelos.me'),
	((select min(id) from User) + 12, 'tar-atanamir@armenelos.me'),
	((select min(id) from User) + 13, 'tar-ancalimon@armenelos.me'),
	((select min(id) from User) + 14, 'tar-telemmaite@armenelos.me'),
	((select min(id) from User) + 15, 'tar-vanimelde@armenelos.me'),
	((select min(id) from User) + 16, 'tar-anducal@armenelos.me'),
	((select min(id) from User) + 17, 'tar-alcarin@armenelos.me'),
	((select min(id) from User) + 18, 'tar-calmacil@armenelos.me'),
	((select min(id) from User) + 19, 'tar-ardamin@armenelos.me'),
	((select min(id) from User) + 20, 'tar-herunumen@armenelos.me'),
	((select min(id) from User) + 21, 'tar-hostamir@armenelos.me'),
	((select min(id) from User) + 22, 'tar-falassion@armenelos.me'),
	((select min(id) from User) + 23, 'tar-telemnar@armenelos.me'),
	((select min(id) from User) + 24, 'tar-palantir@armenelos.me'),
	((select min(id) from User) + 25, 'tar-miriel@armenelos.me'),
	((select min(id) from User) + 26, 'tar-calion@armenelos.me'),
	((select min(id) from User) + 27, 'ingwe@highelves-vanyar.me'),
	((select min(id) from User) + 28, 'finwe@highelves-vanyar.me'),
	((select min(id) from User) + 27, 'ingwe@valinor.aman'),
	((select min(id) from User) + 28, 'finwe@valinor.aman'),
	((select min(id) from User) + 29, 'fangorn@fangorn.me'),
	((select min(id) from User) + 30, 'finglas@fangorn.me'),
	((select min(id) from User) + 31, 'fladrif@fangorn.me'),
	((select min(id) from User) + 32, 'beechbone@fangorn.me'),
	((select min(id) from User) + 33, 'bregalad@fangorn.me'),
	((select min(id) from User) + 34, 'fimbrethil@fangorn.me'),
	((select min(id) from User) + 35, 'witchking@minasmorgul.me'),
	((select min(id) from User) + 36, 'khamul@minasmorgul.me'),
	((select min(id) from User) + 37, 'sarumanwhite@isengard.me');
