/* 
 * Users
 * 
 * 00 - 25: Rulers of Númenor (in student environment role)
 * 26 - 27: Vanyars Ingwë & Finwë (in guest role)
 * 28 - 33: Ents (in teacher role),
 * 34 - 35: Nazgûls (in Servant of Sauron role)
 * 36: Saruman (in Servant of Sauron role)
 * */
insert into User (firstName, lastName, role_id) values 
	('Elros Tar', 'Minyatur', 1),
	('Vardamir', 'Nólimon', 1),
	('Tar', 'Amandil', 1),
	('Tar', 'Elendil', 1),
	('Tar', 'Meneldur Írimon', 1),
	('Tar', 'Aldarion Anardil', 1),
	('Tar', 'Ancalimë', 1),
	('Tar', 'Anárion', 1),
	('Tar', 'Súrion', 1),
	('Tar', 'Telperiën', 1),
	('Tar', 'Minastir', 1),
	('Tar', 'Ciryatan', 1),
	('Tar', 'Atanamir', 1),
	('Tar', 'Ancalimon', 1),
	('Tar', 'Telemmaitë', 1),
	('Tar', 'Vanimeldë', 1),
	('Tar', 'Anducal', 1),
	('Tar', 'Alcarin', 1),
	('Tar', 'Calmacil', 1),
	('Tar', 'Ardamin', 1),
	('Tar', 'Herunúmen', 1),
	('Tar', 'Hostamir', 1),
	('Tar', 'Falassion', 1),
	('Tar', 'Telemnar', 1),
	('Tar', 'Palantir', 1),
	('Tar', 'Míriel', 1),
	('Tar', 'Calion', 1),
	('Ingwë', '', 0),
	('Finwë', '', 0),
	('Fangorn', '', 2),
	('Finglas', '', 2),
	('Fladrif', '', 2),
	('Beechbone', '', 2),
	('Bregalad', '', 2),
	('Fimbrethil', '', 2),
	('Witch-king Of Angmar', '', 3),
	('Khamûl', '', 3),
	('Saruman', 'The White', 3)
	
insert into UserEmail (user_id, address) values 
	(00, 'elros-tar-minyatur@armenelos.me'),
	(01, 'vardamir-nolimon@armenelos.me'),
	(02, 'tar-amandil@armenelos.me'),
	(03, 'tar-elendil@armenelos.me'),
	(04, 'tar-meneldur-irimon@armenelos.me'),
	(05, 'tar-aldarion-anardil@armenelos.me'),
	(06, 'tar-ancalime@armenelos.me'),
	(07, 'tar-anarion@armenelos.me'),
	(08, 'tar-surion@armenelos.me'),
	(09, 'tar-telperien@armenelos.me'),
	(10, 'tar-minastir@armenelos.me'),
	(11, 'tar-ciryatan@armenelos.me'),
	(12, 'tar-atanamir@armenelos.me'),
	(13, 'tar-ancalimon@armenelos.me'),
	(14, 'tar-telemmaite@armenelos.me'),
	(15, 'tar-vanimelde@armenelos.me'),
	(16, 'tar-anducal@armenelos.me'),
	(17, 'tar-alcarin@armenelos.me'),
	(18, 'tar-calmacil@armenelos.me'),
	(19, 'tar-ardamin@armenelos.me'),
	(20, 'tar-herunumen@armenelos.me'),
	(21, 'tar-hostamir@armenelos.me'),
	(22, 'tar-falassion@armenelos.me'),
	(23, 'tar-telemnar@armenelos.me'),
	(24, 'tar-palantir@armenelos.me'),
	(25, 'tar-miriel@armenelos.me'),
	(26, 'tar-calion@armenelos.me'),
	(27, 'ingwe@highelves-vanyar.me'),
	(28, 'finwe@highelves-vanyar.me'),
	(27, 'ingwe@valinor.aman'),
	(28, 'finwe@valinor.aman'),
	(29, 'fangorn@fangorn.me'),
	(30, 'finglas@fangorn.me'),
	(31, 'fladrif@fangorn.me'),
	(32, 'beechbone@fangorn.me'),
	(33, 'bregalad@fangorn.me'),
	(34, 'fimbrethil@fangorn.me'),
	(35, 'witchking@minasmorgul.me'),
	(36, 'khamul@minasmorgul.me'),
	(37, 'sarumanwhite@isengard.me');
