/**
  Insert users to workspaces
**/

insert into WorkspaceUser (workspace_id, user_id) values 
	(8, (select min(id) from User) + 00),
	(8, (select min(id) from User) + 01),
	(8, (select min(id) from User) + 02),
	(8, (select min(id) from User) + 03),
	(8, (select min(id) from User) + 04),
	(8, (select min(id) from User) + 05),
	(8, (select min(id) from User) + 06),
	(8, (select min(id) from User) + 07),
	(8, (select min(id) from User) + 08),
	(8, (select min(id) from User) + 09),
	(8, (select min(id) from User) + 10),
	(8, (select min(id) from User) + 11),
	(8, (select min(id) from User) + 12),
	(8, (select min(id) from User) + 13),
	(8, (select min(id) from User) + 14),
	(8, (select min(id) from User) + 15),
	(8, (select min(id) from User) + 16),
	(8, (select min(id) from User) + 17),
	(8, (select min(id) from User) + 18),
	(8, (select min(id) from User) + 19),
	(8, (select min(id) from User) + 20),
	(8, (select min(id) from User) + 21),
	(8, (select min(id) from User) + 22),
	(8, (select min(id) from User) + 23),
	(8, (select min(id) from User) + 24),
	(8, (select min(id) from User) + 25),
	(8, (select min(id) from User) + 26),
	(1, (select min(id) from User) + 27),
	(2, (select min(id) from User) + 27),
	(1, (select min(id) from User) + 28),
	(2, (select min(id) from User) + 28),
	(11, (select min(id) from User) + 29),
	(11, (select min(id) from User) + 30),
	(11, (select min(id) from User) + 31),
	(11, (select min(id) from User) + 32),
	(11, (select min(id) from User) + 33),
	(11, (select min(id) from User) + 34),
	(12, (select min(id) from User) + 29),
	(12, (select min(id) from User) + 30),
	(12, (select min(id) from User) + 31),
	(12, (select min(id) from User) + 32),
	(12, (select min(id) from User) + 33),
	(12, (select min(id) from User) + 34),
    (12, (select min(id) from User) + 37);