/**
  Insert users to workspaces
**/

insert into WorkspaceUser (workspace_school_data_source, user_school_data_source, workspace_identifier, user_identifier, role_school_data_source, role_identifier) values 
	('MOCK', 'MOCK', '8', '1', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '2', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '3', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '4', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '5', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '6', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '7', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '8', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '9', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '10', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '11', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '12', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '13', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '14', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '15', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '16', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '17', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '18', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '19', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '20', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '21', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '22', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '23', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '24', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '25', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '26', 'MOCK', '5'),
	('MOCK', 'MOCK', '8', '27', 'MOCK', '5'),
	('MOCK', 'MOCK', '1', '28', 'MOCK', '5'),
	('MOCK', 'MOCK', '2', '28', 'MOCK', '5'),
	('MOCK', 'MOCK', '1', '29', 'MOCK', '5'),
	('MOCK', 'MOCK', '2', '29', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '30', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '31', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '32', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '33', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '34', 'MOCK', '5'),
	('MOCK', 'MOCK', '11', '35', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '30', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '31', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '32', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '33', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '34', 'MOCK', '5'),
	('MOCK', 'MOCK', '12', '35', 'MOCK', '5'),
    ('MOCK', 'MOCK', '12', '38', 'MOCK', '5'),
    ('MOCK', 'LOCAL', '20', '2', 'MOCK', '5'),
    ('MOCK', 'LOCAL', '20', '3', 'MOCK', '5');