/**
  Insert users to workspaces
**/

insert into WorkspaceUser (workspace_id, user_id) values 
	((select min(id) from Workspace) + 7, (select min(id) from User) + 00),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 01),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 02),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 03),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 04),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 05),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 06),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 07),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 08),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 09),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 10),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 11),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 12),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 13),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 14),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 15),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 16),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 17),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 18),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 19),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 20),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 21),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 22),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 23),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 24),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 25),
	((select min(id) from Workspace) + 7, (select min(id) from User) + 26),
	((select min(id) from Workspace) + 0, (select min(id) from User) + 27),
	((select min(id) from Workspace) + 1, (select min(id) from User) + 27),
	((select min(id) from Workspace) + 0, (select min(id) from User) + 28),
	((select min(id) from Workspace) + 1, (select min(id) from User) + 28),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 29),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 30),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 31),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 32),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 33),
	((select min(id) from Workspace) + 10, (select min(id) from User) + 34),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 29),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 30),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 31),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 32),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 33),
	((select min(id) from Workspace) + 11, (select min(id) from User) + 34),
    ((select min(id) from Workspace) + 11, (select min(id) from User) + 37);