fail_on_violations: true
javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore
  version: 8.1.0
scss:
  config_file: .scss-lint.yml
  version: 0.57.1
