import { SmowlApi } from "./SmowlApi";
import {
  ActivityConfig,
  AddActivityRequest,
  AddActivityResponse,
  ModifyActivityRequest,
  ModifyActivityResponse,
  GetActiveServicesRequest,
  GetActiveServicesResponse,
  TestExamModeRequest,
  TestExamModeResponse,
  ComputerMonitoringRequest,
  ComputerMonitoringResponse,
  MonitoringAlarmsResponse,
  MonitoringAlarmsSetResponse,
  ComputerMonitoringAlarmsConfig,
  FrontCameraAlarmsConfig,
  SmowlErrorResponse,
  SmowlApiError,
  ExternalCameraRequest,
  ExternalCameraResponse,
  SetMonitoringDeviceAlarmsRequest,
  GetMonitoringDeviceAlarmsRequest,
  MonitoringAlarmsActivityResult,
  ComputerMonitoringAllowedActions,
  ComputerMonitoringAllowedPrograms,
  FrontCameraAlarms,
} from "./types";
import {
  isSmowlApiError,
  objectToFormUrlEncoded,
  createActivityListJson,
  createAlarmsJson,
  createComputerMonitoringAlarmsJson,
  createFrontAlarmHashMap,
  createComputerMonitoringAlarmHashMap,
  formLinkWithJwt,
  generateRegistrationLinkWithJwt,
  generateMonitoringLinkWithJwt,
  getSmowlApiAccountInfo,
  getSmowlApi,
} from "./helper";

export {
  // Api class
  type SmowlApi,

  // Export types
  type ActivityConfig,
  type AddActivityRequest,
  type AddActivityResponse,
  type ModifyActivityRequest,
  type ModifyActivityResponse,
  type GetActiveServicesRequest,
  type GetActiveServicesResponse,
  type TestExamModeRequest,
  type TestExamModeResponse,
  type ExternalCameraRequest,
  type ExternalCameraResponse,
  type ComputerMonitoringRequest,
  type ComputerMonitoringResponse,
  type ComputerMonitoringAllowedActions,
  type ComputerMonitoringAllowedPrograms,
  type FrontCameraAlarms,
  type GetMonitoringDeviceAlarmsRequest,
  type SetMonitoringDeviceAlarmsRequest,
  type FrontCameraAlarmsConfig,
  type ComputerMonitoringAlarmsConfig,
  type MonitoringAlarmsResponse,
  type MonitoringAlarmsSetResponse,
  type MonitoringAlarmsActivityResult,
  type SmowlErrorResponse,
  type SmowlApiError,

  // Helper functions
  isSmowlApiError,
  objectToFormUrlEncoded,
  createActivityListJson,
  createAlarmsJson,
  createComputerMonitoringAlarmsJson,
  createFrontAlarmHashMap,
  createComputerMonitoringAlarmHashMap,
  formLinkWithJwt,
  generateRegistrationLinkWithJwt,
  generateMonitoringLinkWithJwt,
  getSmowlApiAccountInfo,
  getSmowlApi,
};
