import { ExaminationGrade } from "~/@types/shared";

export const ACADEMIC_SUBJECTS = [
  "UE",
  "UO",
  "ET",
  "YO",
  "KE",
  "GE",
  "TT",
  "PS",
  "FI",
  "HI",
  "FY",
  "BI",
];
export const ADVANCED_SUBJECTS = [
  "MAA",
  "RUA",
  "ENA",
  "RAA",
  "ESA",
  "SAA",
  "VEA",
];

export const FINNISH_SUBJECTS = ["AI", "S2", "O5", "Z", "I", "W"];
export const SUBJECT_CODES = [
  "AI",
  "S2",
  "O5",
  "ENA",
  "RAA",
  "ESA",
  "SAA",
  "VEA",
  "RUA",
  "RUB",
  "MAA",
  "MAB",
  "UE",
  "UO",
  "ET",
  "YO",
  "KE",
  "GE",
  "TT",
  "PS",
  "FI",
  "HI",
  "FY",
  "BI",
  "ENC",
  "RAC",
  "ESC",
  "SAC",
  "VEC",
  "ITC",
  "POC",
  "LAC",
  "L7",
  "SM_DC",
  "SM_ICC",
  "SM_QC",
  "Z",
  "I",
  "W",
];

export const EXAMINATION_GRADES_MAP: ExaminationGrade = {
  LAUDATUR: "L (Laudatur)",
  EXIMIA_CUM_LAUDE_APPROBATUR: "E (Eximia cum laude approbatur)",
  MAGNA_CUM_LAUDE_APPROBATUR: "M (Magna cum laude approbatur)",
  CUM_LAUDE_APPROBATUR: "C (Cum laude approbatur)",
  LUBENTER_APPROBATUR: "B (Lubenter approbatur)",
  APPROBATUR: "A (Approbatur)",
  IMPROBATUR: "I (Improbatur)",
  K: "K (Hylätty, muu syy)",
  UNKNOWN: "Ei vielä tiedossa",
};

export const EXAMINATION_SUCCESS_GRADES_MAP = [
  "APPROBATUR",
  "LUBENTER_APPROBATUR",
  "CUM_LAUDE_APPROBATUR",
  "MAGNA_CUM_LAUDE_APPROBATUR",
  "EXIMIA_CUM_LAUDE_APPROBATUR",
  "LAUDATUR",
];
