insert into AuthSource (name, strategy) values ('Pyramus', 'pyramusoauth');
insert into PluginSettingKey(name, plugin) select 'oauth.clientId', 'pyramus-oauth' from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientId' having count(*) = 0;
insert into PluginSettingKey(name, plugin) select 'oauth.clientSecret', 'pyramus-oauth' from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientSecret' having count(*) = 0;
insert into PluginSettingKey(name, plugin) select 'oauth.redirectUrl', 'pyramus-oauth' from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.redirectUrl' having count(*) = 0;
insert into PluginSettingKey(name, plugin) select 'oauth.logoutUrl', 'pyramus-oauth' from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.logoutUrl' having count(*) = 0;
insert into PluginSetting (value, key_id) select '854885cf-2284-4b17-b63c-a8b189535f8d', (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientId') from PluginSetting where key_id = (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientId') having count(*) = 0;
insert into PluginSetting (value, key_id) select 'cqJ4J1if8ca5RMUqaYyFPYToxfFxt2YT8PXL3pNygPClnjJdt55lrFs6k1SZ6colJN24YEtZ7bhFW29S', (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientSecret') from PluginSetting where key_id = (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.clientSecret') having count(*) = 0;
insert into PluginSetting (value, key_id) select 'https://dev.muikku.fi:8443/login?_stg=rsp', (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.redirectUrl') from PluginSetting where key_id = (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.redirectUrl') having count(*) = 0;
insert into PluginSetting (value, key_id) select 'https://dev.pyramus.fi:8443/users/logout.page', (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.logoutUrl') from PluginSetting where key_id = (select id from PluginSettingKey where plugin = 'pyramus-oauth' and name = 'oauth.logoutUrl') having count(*) = 0;
