import { PlannedCourse } from "~/@types/shared";

export const plannedCoursesMock: PlannedCourse[] = [
  {
    id: 1,
    name: "Tekstien tulkinta ja kirjoittaminen",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "ÄI",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2024-08-01"),
  },
  {
    id: 2,
    name: "Ruotsin kieli arjessani 1",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "RUB1",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2024-08-01"),
  },
  {
    id: 3,
    name: "Ruotsin kieli arjessani 2",
    courseNumber: 2,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "RUB1",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2024-08-01"),
  },
  {
    id: 4,
    name: "Opiskelutaidot ja kieli-identiteetin rakentaminen",
    courseNumber: 1,
    length: 1,
    lengthSymbol: "op",
    subjectCode: "ENA",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2024-11-01"),
  },
  {
    id: 5,
    name: "Luvut ja yhtälöt",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "MAY",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2024-11-24"),
  },
  {
    id: 6,
    name: "Matemaattinen analyysi",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "MAY",
    mandatory: false,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-01-01"),
  },
  {
    id: 7,
    name: "Elämä ja evoluutio",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "BI",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-02-05"),
  },
  {
    id: 8,
    name: "Ihminen, ympäristö ja historia",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "HI",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-04-05"),
  },
  {
    id: 9,
    name: "Itsenäisen Suomen historia",
    courseNumber: 2,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "HI",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-05-02"),
  },
  {
    id: 10,
    name: "Kansainväliset suhteet",
    courseNumber: 3,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "HI",
    mandatory: false,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-07-02"),
  },
  {
    id: 11,
    name: "Suomalainen yhteiskunta",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "YH",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-08-02"),
  },
  {
    id: 12,
    name: "Taloustieto",
    courseNumber: 2,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "YH",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-10-02"),
  },
  {
    id: 13,
    name: "Uskonto ilmiönä – juutalaisuuden, kristinuskon ja islamin jäljillä",
    courseNumber: 1,
    length: 2,
    lengthSymbol: "op",
    subjectCode: "UE",
    mandatory: true,
    // 5 weeks
    duration: 5 * 7 * 24 * 60 * 60 * 1000,
    startDate: new Date("2025-11-25"),
  },
];
