/**
 * The list of special characters available in the picker.
 *
 * Mirrors the CKEditor 4 `specialchar` plugin defaults so that users
 * migrating from the legacy editor get a familiar palette.
 */

/**
 * A single entry in the special character grid.
 */
export interface SpecialCharacter {
  /** The actual Unicode character to insert into the document. */
  char: string;
  /** Human-readable label, used as `aria-label` and in the preview pane. */
  label: string;
}

export const SPECIAL_CHARACTERS: SpecialCharacter[] = [
  // ASCII printables (except space, which is not useful here)
  { char: "!", label: "Exclamation mark" },
  { char: '"', label: "Quotation mark" },
  { char: "#", label: "Number sign" },
  { char: "$", label: "Dollar sign" },
  { char: "%", label: "Percent sign" },
  { char: "&", label: "Ampersand" },
  { char: "'", label: "Apostrophe" },
  { char: "(", label: "Left parenthesis" },
  { char: ")", label: "Right parenthesis" },
  { char: "*", label: "Asterisk" },
  { char: "+", label: "Plus sign" },
  { char: "-", label: "Hyphen-minus" },
  { char: ".", label: "Full stop" },
  { char: "/", label: "Solidus" },
  { char: "0", label: "Digit zero" },
  { char: "1", label: "Digit one" },
  { char: "2", label: "Digit two" },
  { char: "3", label: "Digit three" },
  { char: "4", label: "Digit four" },
  { char: "5", label: "Digit five" },
  { char: "6", label: "Digit six" },
  { char: "7", label: "Digit seven" },
  { char: "8", label: "Digit eight" },
  { char: "9", label: "Digit nine" },
  { char: ":", label: "Colon" },
  { char: ";", label: "Semicolon" },
  { char: "<", label: "Less-than sign" },
  { char: "=", label: "Equals sign" },
  { char: ">", label: "Greater-than sign" },
  { char: "?", label: "Question mark" },
  { char: "@", label: "Commercial at" },
  { char: "A", label: "Latin capital letter A" },
  { char: "B", label: "Latin capital letter B" },
  { char: "C", label: "Latin capital letter C" },
  { char: "D", label: "Latin capital letter D" },
  { char: "E", label: "Latin capital letter E" },
  { char: "F", label: "Latin capital letter F" },
  { char: "G", label: "Latin capital letter G" },
  { char: "H", label: "Latin capital letter H" },
  { char: "I", label: "Latin capital letter I" },
  { char: "J", label: "Latin capital letter J" },
  { char: "K", label: "Latin capital letter K" },
  { char: "L", label: "Latin capital letter L" },
  { char: "M", label: "Latin capital letter M" },
  { char: "N", label: "Latin capital letter N" },
  { char: "O", label: "Latin capital letter O" },
  { char: "P", label: "Latin capital letter P" },
  { char: "Q", label: "Latin capital letter Q" },
  { char: "R", label: "Latin capital letter R" },
  { char: "S", label: "Latin capital letter S" },
  { char: "T", label: "Latin capital letter T" },
  { char: "U", label: "Latin capital letter U" },
  { char: "V", label: "Latin capital letter V" },
  { char: "W", label: "Latin capital letter W" },
  { char: "X", label: "Latin capital letter X" },
  { char: "Y", label: "Latin capital letter Y" },
  { char: "Z", label: "Latin capital letter Z" },
  { char: "[", label: "Left square bracket" },
  { char: "]", label: "Right square bracket" },
  { char: "^", label: "Circumflex accent" },
  { char: "_", label: "Low line" },
  { char: "`", label: "Grave accent" },
  { char: "a", label: "Latin small letter a" },
  { char: "b", label: "Latin small letter b" },
  { char: "c", label: "Latin small letter c" },
  { char: "d", label: "Latin small letter d" },
  { char: "e", label: "Latin small letter e" },
  { char: "f", label: "Latin small letter f" },
  { char: "g", label: "Latin small letter g" },
  { char: "h", label: "Latin small letter h" },
  { char: "i", label: "Latin small letter i" },
  { char: "j", label: "Latin small letter j" },
  { char: "k", label: "Latin small letter k" },
  { char: "l", label: "Latin small letter l" },
  { char: "m", label: "Latin small letter m" },
  { char: "n", label: "Latin small letter n" },
  { char: "o", label: "Latin small letter o" },
  { char: "p", label: "Latin small letter p" },
  { char: "q", label: "Latin small letter q" },
  { char: "r", label: "Latin small letter r" },
  { char: "s", label: "Latin small letter s" },
  { char: "t", label: "Latin small letter t" },
  { char: "u", label: "Latin small letter u" },
  { char: "v", label: "Latin small letter v" },
  { char: "w", label: "Latin small letter w" },
  { char: "x", label: "Latin small letter x" },
  { char: "y", label: "Latin small letter y" },
  { char: "z", label: "Latin small letter z" },
  { char: "{", label: "Left curly bracket" },
  { char: "|", label: "Vertical line" },
  { char: "}", label: "Right curly bracket" },
  { char: "~", label: "Tilde" },

  // Currency / punctuation
  { char: "€", label: "Euro sign" },
  { char: "‘", label: "Left single quotation mark" },
  { char: "’", label: "Right single quotation mark" },
  { char: "“", label: "Left double quotation mark" },
  { char: "”", label: "Right double quotation mark" },
  { char: "–", label: "En dash" },
  { char: "—", label: "Em dash" },

  // Latin-1 Supplement
  { char: "¡", label: "Inverted exclamation mark" },
  { char: "¢", label: "Cent sign" },
  { char: "£", label: "Pound sign" },
  { char: "¤", label: "Currency sign" },
  { char: "¥", label: "Yen sign" },
  { char: "¦", label: "Broken bar" },
  { char: "§", label: "Section sign" },
  { char: "¨", label: "Diaeresis" },
  { char: "©", label: "Copyright sign" },
  { char: "ª", label: "Feminine ordinal indicator" },
  { char: "«", label: "Left-pointing double angle quotation mark" },
  { char: "¬", label: "Not sign" },
  { char: "®", label: "Registered sign" },
  { char: "¯", label: "Macron" },
  { char: "°", label: "Degree sign" },
  { char: "±", label: "Plus-minus sign" },
  { char: "²", label: "Superscript two" },
  { char: "³", label: "Superscript three" },
  { char: "´", label: "Acute accent" },
  { char: "µ", label: "Micro sign" },
  { char: "¶", label: "Pilcrow sign" },
  { char: "·", label: "Middle dot" },
  { char: "¸", label: "Cedilla" },
  { char: "¹", label: "Superscript one" },
  { char: "º", label: "Masculine ordinal indicator" },
  { char: "»", label: "Right-pointing double angle quotation mark" },
  { char: "¼", label: "Vulgar fraction one quarter" },
  { char: "½", label: "Vulgar fraction one half" },
  { char: "¾", label: "Vulgar fraction three quarters" },
  { char: "¿", label: "Inverted question mark" },

  // Accented uppercase
  { char: "À", label: "Latin capital letter A with grave" },
  { char: "Á", label: "Latin capital letter A with acute" },
  { char: "Â", label: "Latin capital letter A with circumflex" },
  { char: "Ã", label: "Latin capital letter A with tilde" },
  { char: "Ä", label: "Latin capital letter A with diaeresis" },
  { char: "Å", label: "Latin capital letter A with ring above" },
  { char: "Æ", label: "Latin capital letter AE" },
  { char: "Ç", label: "Latin capital letter C with cedilla" },
  { char: "È", label: "Latin capital letter E with grave" },
  { char: "É", label: "Latin capital letter E with acute" },
  { char: "Ê", label: "Latin capital letter E with circumflex" },
  { char: "Ë", label: "Latin capital letter E with diaeresis" },
  { char: "Ì", label: "Latin capital letter I with grave" },
  { char: "Í", label: "Latin capital letter I with acute" },
  { char: "Î", label: "Latin capital letter I with circumflex" },
  { char: "Ï", label: "Latin capital letter I with diaeresis" },
  { char: "Ð", label: "Latin capital letter Eth" },
  { char: "Ñ", label: "Latin capital letter N with tilde" },
  { char: "Ò", label: "Latin capital letter O with grave" },
  { char: "Ó", label: "Latin capital letter O with acute" },
  { char: "Ô", label: "Latin capital letter O with circumflex" },
  { char: "Õ", label: "Latin capital letter O with tilde" },
  { char: "Ö", label: "Latin capital letter O with diaeresis" },
  { char: "×", label: "Multiplication sign" },
  { char: "Ø", label: "Latin capital letter O with stroke" },
  { char: "Ù", label: "Latin capital letter U with grave" },
  { char: "Ú", label: "Latin capital letter U with acute" },
  { char: "Û", label: "Latin capital letter U with circumflex" },
  { char: "Ü", label: "Latin capital letter U with diaeresis" },
  { char: "Ý", label: "Latin capital letter Y with acute" },
  { char: "Þ", label: "Latin capital letter Thorn" },
  { char: "ß", label: "Latin small letter sharp s" },

  // Accented lowercase
  { char: "à", label: "Latin small letter a with grave" },
  { char: "á", label: "Latin small letter a with acute" },
  { char: "â", label: "Latin small letter a with circumflex" },
  { char: "ã", label: "Latin small letter a with tilde" },
  { char: "ä", label: "Latin small letter a with diaeresis" },
  { char: "å", label: "Latin small letter a with ring above" },
  { char: "æ", label: "Latin small letter ae" },
  { char: "ç", label: "Latin small letter c with cedilla" },
  { char: "è", label: "Latin small letter e with grave" },
  { char: "é", label: "Latin small letter e with acute" },
  { char: "ê", label: "Latin small letter e with circumflex" },
  { char: "ë", label: "Latin small letter e with diaeresis" },
  { char: "ì", label: "Latin small letter i with grave" },
  { char: "í", label: "Latin small letter i with acute" },
  { char: "î", label: "Latin small letter i with circumflex" },
  { char: "ï", label: "Latin small letter i with diaeresis" },
  { char: "ð", label: "Latin small letter eth" },
  { char: "ñ", label: "Latin small letter n with tilde" },
  { char: "ò", label: "Latin small letter o with grave" },
  { char: "ó", label: "Latin small letter o with acute" },
  { char: "ô", label: "Latin small letter o with circumflex" },
  { char: "õ", label: "Latin small letter o with tilde" },
  { char: "ö", label: "Latin small letter o with diaeresis" },
  { char: "÷", label: "Division sign" },
  { char: "ø", label: "Latin small letter o with stroke" },
  { char: "ù", label: "Latin small letter u with grave" },
  { char: "ú", label: "Latin small letter u with acute" },
  { char: "û", label: "Latin small letter u with circumflex" },
  { char: "ü", label: "Latin small letter u with diaeresis" },
  { char: "ý", label: "Latin small letter y with acute" },
  { char: "þ", label: "Latin small letter thorn" },
  { char: "ÿ", label: "Latin small letter y with diaeresis" },

  // Latin Extended-A extras
  { char: "Œ", label: "Latin capital ligature OE" },
  { char: "œ", label: "Latin small ligature oe" },
  { char: "Ŵ", label: "Latin capital letter W with circumflex" },
  { char: "Ŷ", label: "Latin capital letter Y with circumflex" },
  { char: "ŵ", label: "Latin small letter w with circumflex" },
  { char: "ŷ", label: "Latin small letter y with circumflex" },

  // Misc punctuation / symbols
  { char: "‚", label: "Single low-9 quotation mark" },
  { char: "„", label: "Double low-9 quotation mark" },
  { char: "…", label: "Horizontal ellipsis" },
  { char: "™", label: "Trade mark sign" },
  { char: "►", label: "Black right-pointing pointer" },
  { char: "•", label: "Bullet" },
  { char: "→", label: "Rightwards arrow" },
  { char: "⇒", label: "Rightwards double arrow" },
  { char: "⇔", label: "Left right double arrow" },
  { char: "♦", label: "Black diamond suit" },
  { char: "≈", label: "Almost equal to" },
];

/**
 * The number of columns to render the grid with. Matches the legacy
 * CKEditor 4 dialog.
 */
export const SPECIAL_CHARACTERS_COLUMNS = 17;
