name: Course Management headless tests
on: 
  push:
    branches: [java17-tests]
jobs:
  testing:
    env:
      OOM2_USER: ${{secrets.OOM2_USER}}
      OOM2_PASSWORD: ${{secrets.OOM2_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'          
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ secrets.GA_CACHE_KEY }}
      - name: Prepare maven settings
        run: python prepare-maven.py
      - name: Build with Maven
        run: mvn clean install --settings ~/.m2/mySettings.xml -Pdummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,timed-notifications-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - name: Test with headless chrome
        run: |
            cd muikku-atests
            mvn clean verify --settings ~/.m2/mySettings.xml -Dmaven.javadoc.skip=true -Dit.browser=chrome_headless -Dit.package="course/management" -Pui-it
