name: Course Materials Management headless tests
on: 
  pull_request:
    branches: [devel]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn install -Pdummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,evaluation-plugin,timed-notifications-plugin,matriculation-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - name: Test with headless chrome
        run: |
            cd muikku-atests
            mvn verify -Dmaven.javadoc.skip=true -Dsource.skip=true -Dit.browser=chrome_headless -Dit.package="course/materials/management" -Pui-it
