name: Snapshot deploy
on: 
  push:
    branches: [devel]
jobs:
  deploy-snapshot:
    env:
      OOM2_USER: ${{secrets.OOM2_USER}}
      OOM2_PASSWORD: ${{secrets.OOM2_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
          ssh-key: ${{ secrets.GA_DEPLOY_KEY }}
          ssh-strict: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ secrets.GA_CACHE_KEY }}
      - name: Prepare maven settings
        run: python prepare-maven.py
      - name: Build with Maven
        run: mvn clean install --settings ~/.m2/mySettings.xml -Pjndi-mail-plugin,elastic-search-plugin,evaluation-plugin,timed-notifications-plugin,pyramus-plugins,matriculation-plugin
      - name: Deploy snapshot
        run: mvn clean deploy --settings ~/.m2/mySettings.xml -Pjndi-mail-plugin,elastic-search-plugin,evaluation-plugin,timed-notifications-plugin,pyramus-plugins,matriculation-plugin
      - name: Webhook to staging
        run: curl -X POST https://${{ secrets.STAGING_WEBHOOK_USER }}:${{ secrets.STAGING_WEBHOOK_USER_PASS }}@${{ secrets.STAGING_WEBHOOK_URL }}
