name: Snapshot deploy
on: 
  push:
    branches: [devel]
jobs:
  deploy-snapshot:
    env:
      OOM2_USER: ${{secrets.OOM2_USER}}
      OOM2_PASSWORD: ${{secrets.OOM2_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          ssh-key: ${{ secrets.GA_DEPLOY_KEY }}
          ssh-strict: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Prepare maven settings
        run: python prepare-maven.py
      - name: Build with Maven
        run: mvn clean install --settings ~/.m2/mySettings.xml -Pjndi-mail-plugin,elastic-search-plugin,timed-notifications-plugin,pyramus-plugins
      - name: Deploy snapshot
        run: mvn clean deploy --settings ~/.m2/mySettings.xml -Pjndi-mail-plugin,elastic-search-plugin,timed-notifications-plugin,pyramus-plugins
      - name: Webhook to staging
        run: curl -X POST https://${{ secrets.STAGING_WEBHOOK_USER }}:${{ secrets.STAGING_WEBHOOK_USER_PASS }}@${{ secrets.STAGING_WEBHOOK_URL }}
