name: Front-end Code Quality

on:
  # Trigger the workflow on push or pull request,
  pull_request:
    branches: [devel]

jobs:
  run-linters:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_extensions: "ts,tsx"
          eslint_dir: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src

          prettier: true
          prettier_extensions: "ts,tsx"
          prettier_dir: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src
