name: ESlint Code Quality Review
on:
  pull_request:
    branches: devel
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.1

      - name: Install npm@10.2.4
        run: npm install --global npm@10.2.4

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src

      - name: Running ESlint Code Quality Review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts,.tsx'
          level: error
          fail_on_error: true
          workdir: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src

